### ISSUE TITLE
Problems with Node 10

### ISSUE THREAD

**Issue by SirWumpus** [abbr/deasync#100]
On FreeBSD 11, with Node 10, trying to test a package [ssi-logger](https://github.com/ssimicro/ssi-logger) , which uses `deasync` before we migrate to node 10 and having trouble with the build.

* Cloned `deasync`, which itself builds fine and the `test.js` runs happily. 

* With `ssi-logger` the `npm install` fails with an error concerning `nan`, see below.  Noticed that there is a newer version of `nan`,  so this might simply be a version problem.

* Tried `npm install ../deasync` then test `ssi-logger` with that version, but that generates a loader error.

Any insights please?

Anthony

```
In file included from ../core.cc:2:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: error: no member named 'ForceSet' in 'v8::Object'
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
         ~~~  ^
In file included from ../core.cc:2:
../../nan/nan.h:834:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../core.cc:2:
../../nan/nan.h:849:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:164:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../core.cc:2:
../../nan/nan.h:864:18: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return node::MakeCallback(
                 ^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:157:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
In file included from ../core.cc:2:
../../nan/nan.h:1473:31: warning: 'MakeCallback' is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
    return scope.Escape(node::MakeCallback(
                              ^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:171:1: note: 'MakeCallback' has been explicitly marked deprecated here
NODE_DEPRECATED("Use MakeCallback(..., async_context)",
^
/home/achowe/.node-gyp/10.5.0/include/node/node.h:88:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
4 warnings and 1 error generated.
gmake: *** [core.target.mk:97: Release/obj.target/core/core.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System FreeBSD 11.2-RELEASE
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/home/achowe/git/ssi-logger/node_modules/modern-syslog
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

https://www.npmjs.com/package/deasync[37;40mnpm[0m [0m[31;40mERR![0m [0m[35mcode[0m ELIFECYCLE
[0m[37;40mnpm[0m [0m[31;40mERR![0m [0m[35merrno[0m 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m modern-syslog@1.1.4 install: `node-gyp rebuild`
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Exit status 1
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m 
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m Failed at the modern-syslog@1.1.4 install script.
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m This is probably not a problem with npm. There is likely additional logging output above.
[0m
[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m A complete log of this run can be found in:
[0m[37;40mnpm[0m [0m[31;40mERR![0m[35m[0m     /home/achowe/.npm/_logs/2018-08-27T17_39_14_866Z-debug.log
[0m
```

**Comment by SirWumpus** [comment]
I've managed to successfully test `ssi-logger` with a `deasync` that has its dependencies updated; its seems that I initially missed a step before running the tests
```
npm install                    # try normal install
npm install ../deasync   # install local updated build
npm update                  # install remaining packages not installed because of initial build error
TESTALL=YES npm test
```

So the final solution seems that `deasync` need only do `npm update` (updating `nan`) and repackage a new version.

**Comment by abbr** [comment]
[nan version dep spec](https://github.com/abbr/deasync/blob/master/package.json#L16) is compatible with latest nan version so nothing needs to be changed at deasync's end. `npm update` is supposed to be called by installer.

**Comment by SirWumpus** [comment]
ballocks
