### ISSUE TITLE
Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3]

### ISSUE THREAD

**Issue by jmsfez** [abbr/deasync#111]
When running the `npm install deasync` command on Mac OS X, I get the following error.
Can you help me please?

Screen copy of the error (for color rendering):
![image](https://user-images.githubusercontent.com/28300202/56095266-1d10cd80-5edb-11e9-85d4-55c95a8129c3.png)

Text copy of the error (for copy-paste if needed):
```
> deasync@0.1.12 install /Users/jsfez/dev/ebikes-lwc/node_modules/@lwc/jest-transformer/node_modules/deasync
> node ./build.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:389:11)
gyp ERR! stack     at Socket.emit (events.js:189:13)
gyp ERR! stack     at Pipe._handle.close (net.js:597:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jsfez/dev/ebikes-lwc/node_modules/@lwc/jest-transformer/node_modules/deasync
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed
npm WARN acorn-jsx@5.0.1 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deasync@0.1.12 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the deasync@0.1.12 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jsfez/.npm/_logs/2019-04-14T15_28_15_895Z-debug.log
```

**Comment by abbr** [comment]
`npm i deasync@latest` should fix by using pre-compiled binaries.

**Comment by jmsfez** [comment]
Does not work for me:

![image](https://user-images.githubusercontent.com/28300202/56095821-d58d4000-5ee0-11e9-9bcb-0180036a1269.png)

**Comment by abbr** [comment]
I don't know why npm gave you v0.1.12. https://www.npmjs.com/package/deasync shows v0.1.14 as latest:

![image](https://user-images.githubusercontent.com/6158277/56095937-9cc87900-5e96-11e9-9101-ddcdf10c279d.png)

**Comment by jmsfez** [comment]
Is their a way to force the requested version in the command?

**Comment by abbr** [comment]
`npm i deasync@0.1.14`
This is obviously a npm issue. If still not working pls contact npm.
