### ISSUE TITLE
Error: async hook stack has become corrupted

### ISSUE THREAD

**Issue by Wandalen** [abbr/deasync#127]
Hello Abbr! Thanks for supporting such a wonderful package.

I often see C++ exceptions like that. I am sure the reason is `deasync`.
I am wondering is there any chance you will fix it? 

I have seen that on different versions of Nodejs. 100% on all OSs, it has a place to happen.

```javascript
PS C:\Users\project\wHttp> node proto\dwtools\amid\l1.test\Http.test.s
Launching several ( 1 ) test suite(s) ..
    Running test suite ( Tools.mid.NpmTools ) ..
    Located at /C/Users/project/proto/dwtools/amid/l1.test/Http.test.s:159:12
        
         = Message of error#1
            read ECONNRESET
              errno : 'ECONNRESET'
              code : 'ECONNRESET'
              syscall : 'read'

         = Beautified calls stack
            at TLSWrap.onStreamRead (internal/stream_base_commons.js:205:27)
            at Function.module.exports.loopWhile (C:\Users\project\wHttp\node_modules\deasync\index.js:71:23)
            at wConsequence._deasync (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:699:11)
            at wConsequence.deasync (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:742:15)
            at Object.retrieve (C:\Users\project\wHttp\proto\dwtools\amid\l1\http\l1\Basic.s:77:11)
            at Object.retrieve (C:\Users\project\wHttp\proto\dwtools\amid\l1.test\Http.test.s:76:25) *
            at Proxy._run (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Routine.s:302:26)
            at wConsequence.<anonymous> (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Suite.s:1009:20)   
            at wConsequence.thenKeep (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:378:8)
            at wTestSuite._testRoutineRun (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Suite.s:1009:4)  
            at wConsequence.handleRoutine (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Suite.s:536:18)  
            at wConsequence.handleRoutine (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l3\iRoutine.s:191:28)    
            at wConsequence.finallyKeep (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:309:8)
            at wConsequence.take (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:2558:8)
            at wConsequence.timeGot (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l8\gTime.s:264:11)
            at wConsequence.take (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:2558:8)
            at timeEnd (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l8\gTime.s:287:11)
            at Object._time (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l5\fTime.s:53:22)
            at Object.time [as _time] (C:\Users\project\wHttp\node_modules\wprocedure\proto\dwtools\abase\l8_procedure\Namespace.s:292:20)
            at Timeout.time [as _onTimeout] (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l5\fTime.s:95:18)      
            at listOnTimeout (internal/timers.js:549:17)
            at processTimers (internal/timers.js:492:7)

            at wTestSuite._testRoutineRun (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Suite.s:1009:4)  
            at wConsequence.handleRoutine (C:\Users\project\wHttp\node_modules\wTesting\proto\dwtools\atop\tester\l5\Suite.s:536:18)  
            at wConsequence.handleRoutine (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l3\iRoutine.s:191:28)    
            at wConsequence.finallyKeep (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:309:8)
            at wConsequence.take (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:2558:8)
            at wConsequence.timeGot (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l8\gTime.s:264:11)
            at wConsequence.take (C:\Users\project\wHttp\node_modules\wConsequence\proto\dwtools\abase\l9\consequence\Consequence.s:2558:8)
            at timeEnd (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l8\gTime.s:287:11)
            at Object._time (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l5\fTime.s:53:22)
            at Object.time [as _time] (C:\Users\project\wHttp\node_modules\wprocedure\proto\dwtools\abase\l8_procedure\Namespace.s:292:20)
            at Timeout.time [as _onTimeout] (C:\Users\project\wHttp\node_modules\wTools\proto\dwtools\abase\l0\l5\fTime.s:95:18)      
            at listOnTimeout (internal/timers.js:549:17)
            at processTimers (internal/timers.js:492:7)

         = Throws stack
            thrown at Proxy._run @ /C/Users/project/node_modules/wTesting/proto/dwtools/atop/tester/l5/Routine.s:308:43
            thrown at Object._err @ /C/Users/project/node_modules/wTools/proto/dwtools/abase/l0/l3/iErr.s:582:5


        Test check ( TestSuite::Tools.mid.NpmTools / TestRoutine::retrieve / array of different URI # 3 ) ... failed, throwing error
      Failed ( throwing error ) TestSuite::Tools.mid.NpmTools / TestRoutine::retrieve in 5.331s
Error: async hook stack has become corrupted (actual: 11810, expected: 22)
 2: 00007FF7CCF38A78 v8::internal::compiler::Operator::EffectOutputCount+7128
 3: 00007FF7CCF3742A v8::internal::compiler::Operator::EffectOutputCount+1418
 4: 00007FF7CD68D850 v8::internal::Builtins::builtin_handle+323456
 5: 00007FF7CD68CD97 v8::internal::Builtins::builtin_handle+320711
 6: 00007FF7CD68D0D8 v8::internal::Builtins::builtin_handle+321544
 7: 00007FF7CD68CEDE v8::internal::Builtins::builtin_handle+321038
 8: 00007FF7CDB26D4D v8::internal::SetupIsolateDelegate::SetupHeap+546893
 9: 00007FF7CDAABBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
10: 00007FF7CDAABBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
11: 00007FF7CDAABBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
12: 00007FF7CDAABBFC v8::internal::SetupIsolateDelegate::SetupHeap+42748
13: 00007FF7CDAA9131 v8::internal::SetupIsolateDelegate::SetupHeap+31793
14: 00007FF7CDAA8D1C v8::internal::SetupIsolateDelegate::SetupHeap+30748
15: 00007FF7CD5E78A3 v8::internal::Execution::CallWasm+1395
16: 00007FF7CD5E7226 v8::internal::Execution::Call+182
17: 00007FF7CD6B829D v8::Function::Call+605
18: 00007FF7CCF1C0CB napi_wrap+108715
19: 00007FF7CCF6CF04 v8::internal::compiler::TopLevelLiveRange::GetSpillOperand+836
20: 00007FF7CCF6994C uv_run+236
21: 00007FF7CCE74851 v8::internal::interpreter::BytecodeArrayWriter::source_position_table_builder+31777
22: 00007FF7CCEE6433 node::Start+275
23: 00007FF7CCD56A9C RC4_options+340380
24: 00007FF7CDBDED38 v8::internal::SetupIsolateDelegate::SetupHeap+1300536
25: 00007FF97D1B7BD4 BaseThreadInitThunk+20
26: 00007FF97DCACE51 RtlUserThreadStart+33
```

**Comment by papb** [comment]
Possible duplicate of #92, is it?

**Comment by Wandalen** [comment]
Tried that code:
```
function waitPromise(val, time) {
  let result = undefined;
  new Promise(res => {
    setTimeout(() => {
      throw new Error('whatever');
      res(val);
    }, time);
  }).then(r => {
    result = r;
  });
  while(!result) {
    require('deasync').runLoopOnce();
  }
  return result;
}

console.log(waitPromise('my name is Bond, JAMES BOND!', 2000));
```
Unfortunately it didn't throw any C++ exception. So not sure. 
It is related with standard Nodejs network functionality in my case.
Adding few more logs.

**Comment by Wandalen** [comment]
= Message of error#102
    read ECONNRESET
      errno : 'ECONNRESET'
      code : 'ECONNRESET'
      syscall : 'read'
    Failed to bump version of npm config /C/pro/web/Port/module/wLogger/package.json
    Failed to /C/pro/web/Port/module/.will/hook/publish.js
    Failed to call a hook at /C/pro/web/Port/module/wLogger/

 = Beautified calls stack
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:183:27)
    at Function.module.exports.loopWhile (C:\pro\node_modules\deasync\index.js:71:23)
    at wConsequence._deasync (C:\pro\abase\l9\consequence\Consequence.s:712:11)
    at wConsequence.deasyncWait (C:\pro\abase\l9\consequence\Consequence.s:755:15)
    at Object.aboutFromRemote (C:\pro\amid\l3\npm\l1\Tools.s:357:11)
    at Object.onDependency (C:\pro\web\Port\module\.will\hook\NpmPublish.js:105:44)
    at C:\pro\amid\l3\npm\l1\Tools.s:179:17
    at Array.forEach (<anonymous>:null:null)
    at Object.structureFixate (C:\pro\amid\l3\npm\l1\Tools.s:164:27)
    at Object.onChange (C:\pro\amid\l3\npm\l1\Tools.s:113:10)
    at Object._readChangeWrite (C:\pro\amid\l3\npm\l1\Tools.s:385:17)
    at Object.fixate (C:\pro\amid\l3\npm\l1\Tools.s:98:10)
    at wWillCli.onModule (C:\pro\web\Port\module\.will\hook\NpmPublish.js:61:9)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainBase.s:5058:23)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at jsCall (C:\pro\atop\will\MainBase.s:5053:6)
    at wWillCli.hookCall (C:\pro\atop\will\MainBase.s:5037:10)
    at wWillCli.handleEach (C:\pro\atop\will\MainTop.s:1694:17)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:540:23)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli.forSingle (C:\pro\atop\will\MainTop.s:537:12)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:108:34)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at C:\pro\atop\will\MainTop.s:108:13
    at Array.forEach (<anonymous>:null:null)
    at wWillCli._openersCurrentEach (C:\pro\atop\will\MainTop.s:105:25)
    at wWillCli.openersCurrentEach (C:\pro\atop\will\MainTop.s:141:15)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:507:21)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli._commandBuildLike (C:\pro\atop\will\MainTop.s:507:4)
    at wWillCli.commandHookCall (C:\pro\atop\will\MainTop.s:1671:15)
    at wCommandsAggregator.commandPerformParsed (C:\pro\amid\l7\Commands\CommandsAggregator.s:416:14)
    at wCommandsAggregator.commandPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:332:21)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:1986:15)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli.commandWith (C:\pro\atop\will\MainTop.s:1975:4)
    at wCommandsAggregator.commandPerformParsed (C:\pro\amid\l7\Commands\CommandsAggregator.s:416:14)
    at wCommandsAggregator.commandPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:332:21)
    at wConsequence.<anonymous> (C:\pro\amid\l7\Commands\CommandsAggregator.s:285:26)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wCommandsAggregator.commandsPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:285:9)
    at wCommandsAggregator.appArgsPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:218:15)
    at C:\pro\atop\will\MainTop.s:52:15
    at Proxy.Try (C:\pro\abase\l9\consequence\Consequence.s:4526:13)
    at wWillCli.exec (C:\pro\atop\will\MainTop.s:50:4)
    at Function.Exec (C:\pro\atop\will\MainTop.s:30:15)
    at _MainTop_s_ (C:\pro\atop\will\MainTop.s:2309:6)
    at Object.<anonymous> (C:\pro\atop\will\MainTop.s:2311:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11

    at jsCall (C:\pro\atop\will\MainBase.s:5053:6)
    at wWillCli.hookCall (C:\pro\atop\will\MainBase.s:5037:10)
    at wWillCli.handleEach (C:\pro\atop\will\MainTop.s:1694:17)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:540:23)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli.forSingle (C:\pro\atop\will\MainTop.s:537:12)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:108:34)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at C:\pro\atop\will\MainTop.s:108:13
    at Array.forEach (<anonymous>:null:null)
    at wWillCli._openersCurrentEach (C:\pro\atop\will\MainTop.s:105:25)
    at wWillCli.openersCurrentEach (C:\pro\atop\will\MainTop.s:141:15)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:507:21)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli._commandBuildLike (C:\pro\atop\will\MainTop.s:507:4)
    at wWillCli.commandHookCall (C:\pro\atop\will\MainTop.s:1671:15)
    at wCommandsAggregator.commandPerformParsed (C:\pro\amid\l7\Commands\CommandsAggregator.s:416:14)
    at wCommandsAggregator.commandPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:332:21)
    at wConsequence.<anonymous> (C:\pro\atop\will\MainTop.s:1986:15)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wWillCli.commandWith (C:\pro\atop\will\MainTop.s:1975:4)
    at wCommandsAggregator.commandPerformParsed (C:\pro\amid\l7\Commands\CommandsAggregator.s:416:14)
    at wCommandsAggregator.commandPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:332:21)
    at wConsequence.<anonymous> (C:\pro\amid\l7\Commands\CommandsAggregator.s:285:26)
    at wConsequence.thenKeep (C:\pro\abase\l9\consequence\Consequence.s:394:8)
    at wCommandsAggregator.commandsPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:285:9)
    at wCommandsAggregator.appArgsPerform (C:\pro\amid\l7\Commands\CommandsAggregator.s:218:15)
    at C:\pro\atop\will\MainTop.s:52:15
    at Proxy.Try (C:\pro\abase\l9\consequence\Consequence.s:4526:13)
    at wWillCli.exec (C:\pro\atop\will\MainTop.s:50:4)
    at Function.Exec (C:\pro\atop\will\MainTop.s:30:15)
    at _MainTop_s_ (C:\pro\atop\will\MainTop.s:2309:6)
    at Object.<anonymous> (C:\pro\atop\will\MainTop.s:2311:3)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)
    at internal/main/run_main_module.js:17:11

 = Throws stack
    thrown at Object.fixate @ /C/pro/dwtools/amid/l3/npm/l1/Tools.s:105:13
    thrown at wConsequence.{-anonymous-} @ /C/pro/dwtools/atop/will/MainBase.s:5074:15
    thrown at wConsequence.syncMaybe @ /C/pro/dwtools/abase/l9/consequence/Consequence.s:1243:15
    thrown at wConsequence.{-anonymous-} @ /C/pro/dwtools/atop/will/MainTop.s:547:15
    thrown at wConsequence.end @ /C/pro/dwtools/atop/will/MainTop.s:562:19
    thrown at Object.onToStr @ /C/pro/dwtools/abase/l9/printer/PrinterBase.s:251:15


Error: async hook stack has become corrupted (actual: 67214, expected: 1)
 1: 00007FF7F7AAAA8F napi_wrap+122063
 2: 00007FF7F7A1C469 v8::internal::Scope::locals+29113
 3: 00007FF7F7A770D3 node::Start+275
 4: 00007FF7F793C8DC AES_cbc_encrypt+15116
 5: 00007FF7F874CEA8 v8::internal::CodeStubAssembler::WordIsPowerOfTwo+151192
 6: 00007FF9374C7BD4 BaseThreadInitThunk+20
 7: 00007FF937F2CED1 RtlUserThreadStart+33
