### ISSUE TITLE
io.js support?

### ISSUE THREAD

**Issue by psi-4ward** [abbr/deasync#13]
Io.JS: v1.6.4
NPM:  v2.7.5

`npm install deasync` fails with

```
227 verbose rebuildBundles deasync@0.0.10
228 verbose rebuildBundles [ 'bindings', 'nan' ]
229 info install deasync@0.0.10
230 verbose unsafe-perm in lifecycle false
231 info deasync@0.0.10 Failed to exec install script
232 verbose unlock done using /root/.npm/_locks/deasync-ef8dd4a1ab973500.lock for /root/node_modules/deasync
233 verbose stack Error: deasync@0.0.10 install: `node ./build.js`
233 verbose stack Exit status 1
233 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
233 verbose stack     at emitTwo (events.js:87:13)
233 verbose stack     at EventEmitter.emit (events.js:169:7)
233 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:14:12)
233 verbose stack     at emitTwo (events.js:87:13)
233 verbose stack     at ChildProcess.emit (events.js:169:7)
233 verbose stack     at maybeClose (child_process.js:984:16)
233 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1057:5)
234 verbose pkgid deasync@0.0.10
235 verbose cwd /root
236 error Linux 3.18.11-1-MANJARO
237 error argv "/usr/bin/iojs" "/usr/bin/npm" "install" "deasync"
238 error node v1.6.4
239 error npm  v2.7.5
240 error code ELIFECYCLE
241 error deasync@0.0.10 install: `node ./build.js`
241 error Exit status 1
242 error Failed at the deasync@0.0.10 install script 'node ./build.js'.
242 error This is most likely a problem with the deasync package,
242 error not with npm itself.
242 error Tell the author that this fails on your system:
242 error     node ./build.js
242 error You can get their info via:
242 error     npm owner ls deasync
242 error There is likely additional logging output above.
```

**Comment by 0x4139** [comment]
check the pull request just update the nan version seems that the owner isn't really replying

**Comment by abbr** [comment]
Cannot reproduce. Installed Io.JS v1.6.4 on a pristine Ubuntu 14.04 x64 server, then run `npm install deasync` succeeded.

**Comment by psi-4ward** [comment]
i was on AlpineLinux docker container - perhaps of the musl libc?

**Comment by abbr** [comment]
Installed iojs@1.6.4 and deasync on gliderlabs/alpine docker successfully. Make sure you meet the prerequisites such as python 2.7, g++ etc which by default alpine don't provide. If you can install io.js from source, you should be able to install deasync.
