### ISSUE TITLE
Error:  Could not locate the bindings file

### ISSUE THREAD

**Issue by tnrich** [abbr/deasync#142]
Hey there, 

I'm getting the following error trying to start my app: 

```
/Users/tnrich/Sites/lims/app-proxy/node_modules/bindings/bindings.js:126
  err = new Error(
        ^

Error: Could not locate the bindings file. Tried:
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/Debug/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/Release/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/out/Debug/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/Debug/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/out/Release/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/Release/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/default/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/compiled/15.8.0/darwin/arm64/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/lib/binding/node-v88-darwin-arm64/deasync.node
    at bindings (/Users/tnrich/Sites/lims/app-proxy/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/index.js:30:31)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/tnrich/Sites/lims/app-proxy/node_modules/node-etcd/lib/client.js:7:11)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/tnrich/Sites/lims/app-proxy/node_modules/node-etcd/lib/index.js:9:10)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18) {
  tries: [
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/Debug/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/Release/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/out/Debug/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/Debug/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/out/Release/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/Release/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/build/default/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/compiled/15.8.0/darwin/arm64/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/release/install-root/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/debug/install-root/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/addon-build/default/install-root/deasync.node',
    '/Users/tnrich/Sites/lims/app-proxy/node_modules/deasync/lib/binding/node-v88-darwin-arm64/deasync.node'
  ]
}
error Command failed with exit code 1.
```

on new apple M1 
node v15.8.0

Any ideas on how to fix this? 
Thanks!

**Comment by vkabish** [comment]
Same for me
apple m1
node v14.15.5

**Comment by halfnibble** [comment]
We noticed this after a code change brought in a dependency that had a dependency on deasync to a project that also had a dependency on deasync. Reverting that seemed to resolve the problem for us, but I don't know why having two dependencies on deasync would create this problem.

**Comment by malisbad** [comment]
I'm also getting this issue. Deasync is a dependency of `cypress-testrail-reporter`, and installing `deasync` as a direct dependency did not resolve the issue.

Node Version: `14.15.4`
Deasync Version: `0.1.21`
`cypress-testrail-reporter` Version: `1.2.7`

**Comment by chaoyangnz** [comment]
the same

**Comment by ackvf** [comment]
Still causing errors

**Comment by trusktr** [comment]
Is this because apple silicon is not supported yet?
