### ISSUE TITLE
Failed at the deasync@0.0.10 install script 'node ./build.js'

### ISSUE THREAD

**Issue by MaximeNicole** [abbr/deasync#35]
Hello,

When I install this module with node v5.0.0 I get this error :+1: 
Failed at the deasync@0.0.10 install script 'node ./build.js'

```
5898 silly install deasync /Users/mnicole/Projects/rpi-gsm-print/node_modules/.staging/deasync-e4547bd165efd9ec12e8d632bec051b9
5899 info lifecycle deasync@0.0.10~install: deasync@0.0.10
5900 verbose lifecycle deasync@0.0.10~install: unsafe-perm in lifecycle true
5901 verbose lifecycle deasync@0.0.10~install: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mnicole/Projects/rpi-gsm-print/node_modules/deasync/node_modules/.bin:/Users/mnicole/Projects/rpi-gsm-print/node_modules/.bin:/Users/mnicole/drush:/Library/Ruby/Gems/2.0.0/gems/compass-1.0.3/bin:/Library/Ruby/Gems/2.0.0/gems/sass-3.4.14/bin/:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
5902 verbose lifecycle deasync@0.0.10~install: CWD: /Users/mnicole/Projects/rpi-gsm-print/node_modules/deasync
5903 silly lifecycle deasync@0.0.10~install: Args: [ '-c', 'node ./build.js' ]
5904 silly lifecycle deasync@0.0.10~install: Returned: code: 1  signal: null
5905 info lifecycle deasync@0.0.10~install: Failed to exec install script
5906 verbose unlock done using /Users/mnicole/.npm/_locks/staging-85d8a68bc79d4dbb.lock for /Users/mnicole/Projects/rpi-gsm-print/node_modules/.staging
5907 silly rollbackFailedOptional Starting
5908 silly rollbackFailedOptional Finishing
5909 silly runTopLevelLifecycles Starting
5910 silly runTopLevelLifecycles Finishing
5911 silly install printInstalled
5912 verbose stack Error: deasync@0.0.10 install: `node ./build.js`
5912 verbose stack Exit status 1
5912 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
5912 verbose stack     at emitTwo (events.js:87:13)
5912 verbose stack     at EventEmitter.emit (events.js:172:7)
5912 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5912 verbose stack     at emitTwo (events.js:87:13)
5912 verbose stack     at ChildProcess.emit (events.js:172:7)
5912 verbose stack     at maybeClose (internal/child_process.js:818:16)
5912 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
5913 verbose pkgid deasync@0.0.10
```

Can you help me to resolve this problem ?

Thanks !

**Comment by tjwebb** [comment]
+1, also happens on node 4.2

**Comment by abbr** [comment]
Can you upgrade to `deasync@v0.1.2` and try again?

**Comment by gjoris** [comment]
Also happens on node 5.1. I have upgraded to deasync@v0.1.4, same result.

**Comment by MaximeNicole** [comment]
I update to deasync@v0.1.3 and it's work perfect !

**Comment by abbr** [comment]
`deasync@0.1.4` comes with pre-compiled binaries for `Node@5` so should work better.
