### ISSUE TITLE
Installing with npm 2.5.1 fails

### ISSUE THREAD

**Issue by jblack10101** [abbr/deasync#4]
Using npm 2.5.1, installation of version 0.0.9 fails when executing:

```
npm install --save-dev deasync
```
It also fails for the previous versions as well.  Here's a snippet of the npm-debug.log.  Let me know if you need more information:
```
238 verbose stack Error: deasync@0.0.9 install: `node ./build.js`
238 verbose stack Exit status 1
238 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
238 verbose stack     at EventEmitter.emit (events.js:110:17)
238 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
238 verbose stack     at ChildProcess.emit (events.js:110:17)
238 verbose stack     at maybeClose (child_process.js:1008:16)
238 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
239 verbose pkgid deasync@0.0.9
240 verbose cwd C:\ws\sniads
241 error Windows_NT 6.1.7601
242 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "deasync"
243 error node v0.12.0
244 error npm  v2.5.1
245 error code ELIFECYCLE
246 error deasync@0.0.9 install: `node ./build.js`
246 error Exit status 1
247 error Failed at the deasync@0.0.9 install script 'node ./build.js'.
247 error This is most likely a problem with the deasync package,
247 error not with npm itself.
```

**Comment by abbr** [comment]
Just published a new release with pre-compiled binaries. Give it a shot. If still not working, follow instructions in readme to install the prerequisites including python, Visual Studio etc.

**Comment by jblack10101** [comment]
Works now, thanks!
