### ISSUE TITLE
Could not locate bindings file

### ISSUE THREAD

**Issue by m-teslya** [abbr/deasync#6]
When I'm trying to run project with deasync module, on application start I get:
```
/opt/website/my-proj/node_modules/deasync/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /opt/website/my-proj/node_modules/deasync/build/deasync.node
 → /opt/website/my-proj/node_modules/deasync/build/Debug/deasync.node
 → /opt/website/my-proj/node_modules/deasync/build/Release/deasync.node
 → /opt/website/my-proj/node_modules/deasync/out/Debug/deasync.node
 → /opt/website/my-proj/node_modules/deasync/Debug/deasync.node
 → /opt/website/my-proj/node_modules/deasync/out/Release/deasync.node
 → /opt/website/my-proj/node_modules/deasync/Release/deasync.node
 → /opt/website/my-proj/node_modules/deasync/build/default/deasync.node
 → /opt/website/my-proj/node_modules/deasync/compiled/0.11.14/linux/x64/deasync.node
    at bindings (/opt/website/my-proj/node_modules/deasync/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/opt/website/my-proj/node_modules/deasync/index.js:13:31)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/opt/website/my-proj/db/methods/users.js:10:15)
    at Module._compile (module.js:460:26)
```
Here's what directory browsing gives me:
```
$ ls ./node_modules/deasync/
bin  binding.gyp  build.js  index.js  node_modules  package.json  quick-test.js  README.md  src  test.js
```
```
$ ls ./node_modules/deasync/bin/
darwin-x64  linux-ia32  linux-x64  win32-ia32  win32-x64
```
OS version:
```
$ cat /proc/version 
Linux version 3.8.13-44.el6uek.x86_64 (mockbuild@ca-build44.us.oracle.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #2 SMP Fri Aug 8 21:59:01 PDT 2014
```
Node version:
```
$ node --version
v0.11.14
```
npm version:
```
$ npm --version
2.0.0
```

**Comment by abbr** [comment]
Have you tried to re-install deasync? From directory structure I can tell the version of deasync is a little outdated.

**Comment by m-teslya** [comment]
I think, I'm using last version of deasync module. Here's package.json from node_modules/deasync:
```
{
  "name": "deasync",
  "version": "0.0.10",
  "description": "Turns async function into sync via JavaScript wrapper of Node event loop",
  "main": "index.js",
  "author": {
    "name": "Vladimir Kurchatkin",
    "email": "vladimir.kurchatkin@gmail.com"
  },
  "contributors": [
    {
      "name": "Fred Wen",
      "email": "wenfred@gmail.com",
      "url": "https://github.com/abbr"
    }
  ],
  "license": "MIT",
  "scripts": {
    "install": "node ./build.js"
  },
  "dependencies": {
    "bindings": "~1.1.1",
    "nan": "^1.6.1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/abbr/deasync.git"
  },
  "homepage": "https://github.com/abbr/deasync",
  "keywords": [
    "async",
    "sync",
    "sleep",
    "async wrapper"
  ],
  "gitHead": "a344118b6053c4de7bf9ee5b2ebd422193767329",
  "bugs": {
    "url": "https://github.com/abbr/deasync/issues"
  },
  "_id": "deasync@0.0.10",
  "_shasum": "80649cee7f41685f976c65531c7a641e397cf5af",
  "_from": "deasync@0.0.10",
  "_npmVersion": "1.4.28",
  "_npmUser": {
    "name": "abbr",
    "email": "wenfred@gmail.com"
  },
  "maintainers": [
    {
      "name": "abbr",
      "email": "wenfred@gmail.com"
    }
  ],
  "dist": {
    "shasum": "80649cee7f41685f976c65531c7a641e397cf5af",
    "tarball": "http://registry.npmjs.org/deasync/-/deasync-0.0.10.tgz"
  },
  "directories": {},
  "_resolved": "https://registry.npmjs.org/deasync/-/deasync-0.0.10.tgz"
}
```

**Comment by abbr** [comment]
deasync@0.0.10 should have [this dir structure](https://github.com/abbr/deasync-bin) under bin/. Uninstall first before re-install.

**Comment by m-teslya** [comment]
Ok, it seems, this did the trick
run:
```
npm uninstall deasync
```
then
```
npm install
```
And it works. Thank you for your help

**Comment by snagine** [comment]
Hi 

I am getting the same error. 
"deasync": "^0.1.10"
"cypress-testrail-reporter": "^1.3.3"
"cypress-cucumber-preprocessor": "^4.2.0"

I tried uninstalling 
npm uninstall deasync
npm install deasync

I still get the error:

The error we received was:

Error: Could not locate the bindings file. Tried:
 → ./node_modules/deasync/build/deasync.node

**Comment by jliujack** [comment]
refer to this jest issues, it may solve a type of problem
https://github.com/facebook/jest/issues/1694#issuecomment-257113870
