### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by akazakou** [abbr/deasync#8]
When i tty using this code
```
        while(!result) {
            require('deasync').runLoopOnce();
        }
```
my app crashed with 
```
symbol lookup error: /home/apache2/zul.dev/www/node_modules/deasync/bin/linux-x64-node-0.11/deasync.node: undefined symbol: _ZN2v86Object3SetENS_6HandleINS_5ValueEEES3_NS_17PropertyAttributeE
```

Ubuntu 14.04
Node v0.10.33
Linux zx386-nb 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by abbr** [comment]
Can you install same deasync version to a different folder on the same server and compare deasync/bin/linux-x64-node-0.11/deasync.node?

**Comment by akazakou** [comment]
Sorry for incorrect data. I use node-webkit for developing desctop application. Lates node-webkit build on Node.JS v0.11.13-pre

**Comment by akazakou** [comment]
When i try rebuild module for node-webkit by manual https://github.com/nwjs/nw.js/wiki/Using-Node-modules , i have en error of compilation:
```
akazakov@zx386-nb:/home/apache2/zul.dev/www/node_modules/deasync$ sudo nw-gyp rebuild --target=0.5.0
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.12.4
gyp info using node@0.10.33 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/apache2/zul.dev/www/node_modules/deasync/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/akazakov/.nw-gyp/0.5.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/akazakov/.nw-gyp/0.5.0',
gyp info spawn args   '-Dmodule_root_dir=/home/apache2/zul.dev/www/node_modules/deasync',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Вход в каталог `/home/apache2/zul.dev/www/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
../src/deasync.cc: In function ‘v8::Handle<v8::Value> Run(const v8::Arguments&)’:
../src/deasync.cc:15:29: error: ‘UV_RUN_ONCE’ was not declared in this scope
   uv_run(uv_default_loop(), UV_RUN_ONCE);
                             ^
make: *** [Release/obj.target/deasync/src/deasync.o] Ошибка 1
make: Выход из каталога `/home/apache2/zul.dev/www/node_modules/deasync/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/nw-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Linux 3.13.0-45-generic
gyp ERR! command "node" "/usr/bin/nw-gyp" "rebuild" "--target=0.5.0"
gyp ERR! cwd /home/apache2/zul.dev/www/node_modules/deasync
gyp ERR! node -v v0.10.33
gyp ERR! nw-gyp -v v0.12.4
gyp ERR! not ok 
```

**Comment by abbr** [comment]
nw.js and nw-gyp are offsprings of node/node-gyp so they are supposed to ensure compatibility. `deasync` compiles fine in node but not in nw is a clear indication such compatibility is broken. You should therefore file the bug to them, not to `deasync`.

**Comment by akazakou** [comment]
![Okay](http://i.imgur.com/42G7fd8.jpg)
